listener 1883
allow_anonymous true

listener 8883
allow_anonymous false
cafile   /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile  /mosquitto/config/certs/server.key
password_file /mosquitto/config/passwd
tls_version tlsv1.2
